services:
    web:
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - .:/var/www
    db:
        image: mysql:8.0
        volumes:
            - .docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret

